### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by AnonymousPuppy** [coolAlias/ZeldaSwordSkills#33]
I'm using a custom modpack, forge .1240, and 1.7.10-zeldaswordskills-0.2.0.jar. I got this random server crash. It seems to be related to the darknut mob, but it could be something else. I'd appreciate it if you could take a look.

Here is the crash report: http://pastebin.com/idrtiZjh

Please take a look at this whenever possible, thank you! :)

**Comment by coolAlias** [comment]
Thanks for the report - I'm on it!

**Comment by coolAlias** [comment]
Closing this issue as I am unable to reproduce it and have had no other reports of it.
