### ISSUE TITLE
Customnpcs Bug

### ISSUE THREAD

**Issue by JustNoah02** [coolAlias/ZeldaSwordSkills#35]
Hi.
I found a bug with customnpcs. I am making a map with this mod and customnpcs, but if i reopen the map, weird stuff happens. The drops of the npcs change into things of the mod and armor dissappears.

**Comment by coolAlias** [comment]
I don't see how that's my issue - it sounds like you are swapping mods in and out of your map and the item mappings are getting messed up as a result.
