### ISSUE TITLE
Bomb Bag goes to "No Texture" Texture if you put in 9 Bombs

### ISSUE THREAD

**Issue by wilfurdmcwargnash** [coolAlias/ZeldaSwordSkills#38]
Example:
![2015-06-25_08 32 51](https://cloud.githubusercontent.com/assets/12634546/8358446/0ef91e22-1b15-11e5-8614-c745b2849170.png)

i am running the latest 1.8 version

**Comment by coolAlias** [comment]
Fixed for next version, thanks!
