### ISSUE TITLE
Song of Storms can't be used in Mystcraft Ages

### ISSUE THREAD

**Issue by Zsashas** [coolAlias/ZeldaSwordSkills#43]
I haven't found an age that it WASN'T raining in yet, but it seems that the Song of Storms can not be used to stop the rain. It gives the cooldown message in the chat when I try, no matter how long it has actually been.

**Comment by coolAlias** [comment]
If a mod adds a dimension in which it is ALWAYS raining, would you really expect the Song of Storms to be able to prevent that? There isn't any way for me to check if that is the case, however, so if you use it, it will still have the cooldown.
