### ISSUE TITLE
Request: Play Warp Songs at destination

### ISSUE THREAD

**Issue by Zsashas** [coolAlias/ZeldaSwordSkills#46]
The teleport songs are nice to listen to, but unless you play it a second time, you usually don't get to hear it all the way through. Perhaps have it play at the set destination as well as at the location played at.

**Comment by coolAlias** [comment]
That could be nice, let me think of a way to do it without making things weird: e.g. if I start the song playing at the destination at the same time as it starts at the origin, then players at the destination will begin hearing the song before anyone shows up.

It may be better in this case to only play the song at the destination for the original player; players at the origin will hear the player play the song, but no one at the destination (other than the teleporting player) will hear anything.

**Comment by coolAlias** [comment]
Would it be acceptable to play the song from the beginning upon arriving, rather than from where it left off? I tried it out and personally, I think it's a little bit weird / disjointed, but maybe you and others would like it. I wasn't a huge fan of the effect.

To do it 'properly' would require a LOT more work, and frankly I don't think it would be worth it.

If you just want to listen to the song, you can always do so either by playing it on the Fairy Ocarina or by sneaking when you open the music interface.

**Comment by Zsashas** [comment]
Perhaps have three config-switchable modes:

Play the song completely at the origin.
Play the song completely, starting upon arrival.


Alternatively, is there a way to have the song only play for that player? If so, then make the song play everywhere for them, and only at the origin for everyone else.

**Comment by coolAlias** [comment]
Not a bad idea, but the songs are implemented as records, which are positioned sounds, and as far as I am aware there is not any way to play a record so it can be heard everywhere at once.

The more I look into this, the less I want to mess with it. If I suddenly figure out how to do it without having to rewrite tons of stuff (this has been known to happen), I'll do it, but until then, I am not going to touch this. There are simply too many technical issues that come up for what should be a simple effect, and I'd rather spend my time on other things.

**Comment by Zsashas** [comment]
That's what I thought. Also, good to know about shift-right clicking the Ocarina.

**Comment by Zsashas** [comment]
I just noticed that when sneak-playing the Ocarina, the sound plays everywhere. It's only localised like a record when it's a functional song.

**Comment by coolAlias** [comment]
You are mistaken, it plays exactly the same as if you didn't sneak, but it has no effect when it completes. Play a longer song, such as the Minuet of the Forest, and as soon as the GUI closes, start flying away as fast as you can and you will notice it the volume fading as your distance increases.

**Comment by coolAlias** [comment]
I'm going to close this for now since, due to the complications I mentioned above, I don't plan to implement it.
