### ISSUE TITLE
Gossip Stone Glitch

### ISSUE THREAD

**Issue by ChristopherTylerGale** [coolAlias/ZeldaSwordSkills#47]
Not entirely sure if it is a glitch, but I have re-installed everything at least twice to try and fix.
While wearing the Mask of Truth, and interacting with the Gossip Stone, the message 'chat.block.gossip_stone.hint.#' pops up.

Is something actually meant to be displayed there? Or is that what is strangely meant to be displayed?

![2015-10-17_16 22 01](https://cloud.githubusercontent.com/assets/7466959/10557142/4777a91e-74eb-11e5-9937-82155e5f0ab8.png)

**Comment by coolAlias** [comment]
Oops, that's the result of some find/replace action that didn't get fixed... thanks for pointing that out - it will be fixed in the next release.

**Comment by coolAlias** [comment]
Resolved by commit 084d3014
