### ISSUE TITLE
The Arrow Merchant Sells, or Buys? (Fire, Ice, Light Arrows)

### ISSUE THREAD

**Issue by ChristopherTylerGale** [coolAlias/ZeldaSwordSkills#49]
The manual says you can buy arrows from the priests when you show then a hero's bow. All I can do is sell them my arrows...
Did you accidentally reverse the coding, or am I just not reading the manual correctly.

(BTW, Love using the mod, hence my third bug report. I would love to see more come from it)

**Comment by coolAlias** [comment]
Oh wow, yeah, it's totally backwards in the code... oops :$ Thanks for the bug reports!
