### ISSUE TITLE
Keese damage sound

### ISSUE THREAD

**Issue by Zsashas** [coolAlias/ZeldaSwordSkills#52]
When Keese take damage, they seem to be making the sword swinging sound from when targeting is active. I was using a Shadowbeam Wand Focus at the time, without targeting (Thaumic Tinkerer)

**Comment by coolAlias** [comment]
That's the sound of a sword swinging through empty air - i.e. you didn't hit them due to their evasion, and they don't actually take damage in such cases. You're welcome to come up with a better sound to represent that.

**Comment by Zsashas** [comment]
Oh ok. I thought it was just using the wrong sound. That makes sense.
