### ISSUE TITLE
Hookshot, clawshot, whip, mirror, not working when running with Mine&Blade: Battlegear 2

### ISSUE THREAD

**Issue by Mumberthrax** [coolAlias/ZeldaSwordSkills#53]
Attempting to use the hookshot, clawshot, whip, and magic mirror while mine&blade is installed seems to achieve no effect. I'm not certain if this is an issue with Battlegear2 or with ZSS.

running mc 1.8; forge 11.14.4.1563; ZSS 3.0.3b; M&B 1.0.9.0

(edit: same results in forge 11.14.3.1450; 11.14.3.1464)

steps to duplicate:

* install both mods.
* create a new creative world
* give yourself the hookshot item, the clawshot, the whip, and the magic mirror.
* place a wooden block in the world, such as oak planks or a wood log.
* place a "beam" block from the zelda sword skills mod someplace, several meters up.
* place a stone block somewhere in the world, cobblestone or smoothstone
* put the hookshot, whip, or clawshot in the hotbar, or in the mine&blade offhand inventory slot
* aim the hookshot at the wood, right click and hold.
* aim the clawshot at the stone, right click and hold.
* aim the whip at the beam, right click and hold.
* hold the magic mirror, right click and hold

To observe intended effects, remove the Mine & Blade: Battlegear 2 mod from the minecraft instance and repeat the above steps.

This is a cross-posted issue from the BG2 github, since I as a layman end-user don't know which mod the bug belongs to. https://github.com/Mine-and-blade-admin/Battlegear2/issues/212

**Comment by coolAlias** [comment]
Known issue, already fixed by BG2. See https://github.com/Mine-and-blade-admin/Battlegear2/issues/206
