### ISSUE TITLE
Netherworld secret room do not spawn Why ?

### ISSUE THREAD

**Issue by Amsterdam1910** [coolAlias/ZeldaSwordSkills#55]
I installed all the things that you have written but in 1.8 zss version when I spawn in Netherworld there is no secret room ! So I just let the generation of keys and dungon mixed up ... I would like you to answer please ! Have a nice christmas time and thank you for that beautiful mod!

**Comment by coolAlias** [comment]
Sorry, it's a [bug with Forge](https://github.com/MinecraftForge/MinecraftForge/issues/2197) that for some reason they haven't patched yet for 1.8.

I may work around the bug in a future release, but for now the Nether does not have any secret rooms.

**Comment by Amsterdam1910** [comment]
Thank you for the answer I hope they'll soon patch that bug ! Merry Christmas !

**Comment by coolAlias** [comment]
I've got a temporary fix for 1.8.0, but I'll probably be updating directly to 1.8.9 instead in which this is no longer an issue. Apologies to all 1.8.0 users that have put up with this for so long :(
