### ISSUE TITLE
typo in command syntax info in /help menu (zssweaponregistry)

### ISSUE THREAD

**Issue by usafphoenix** [coolAlias/ZeldaSwordSkills#56]
syntax info found in /help for minecraft lists command for ZSS weapon registry to be "add|remove"
instead of "allow|forbid"

**Comment by usafphoenix** [comment]
using "add|remove" when typing in command as info suggests causes error. using allow|forbid, completes action as intended.

**Comment by coolAlias** [comment]
Thanks, got the docs backwards, it seems.

**Comment by usafphoenix** [comment]
glad to help.
