### ISSUE TITLE
Make shields function like the new 1.9 ones

### ISSUE THREAD

**Issue by sonicdahedghog** [coolAlias/ZeldaSwordSkills#61]
Shields have come to 1.9 previously, and I thought that it would be cool when you update this mod to 1.9 if the shields were able to function like they do in 1.9. And it would be a great idea because you can now change your main hand in the game to right or left! But you wouldn't be able to import banner designs onto the shields.

**Comment by coolAlias** [comment]
Seriously? It's been what, a day? And what's different about the way 1.9 shields work vs. the way my shields are right now?

**Comment by sonicdahedghog** [comment]
.... because you can use both hands at once?

**Comment by sonicdahedghog** [comment]
Goodbye!!! I have better things to worry about than you and your mod!!!
