### ISSUE TITLE
[1.7.10] Clay Jar bug

### ISSUE THREAD

**Issue by Zsashas** [coolAlias/ZeldaSwordSkills#64]
Right-clicking to pick up a jar placed in the world destroys anything it might have had inside. I don't know if there's a way to check if it has something inside, though.

**Comment by coolAlias** [comment]
It shouldn't. That is something I specifically tested when creating the jar. Are you sure you just didn't see where the item spawned in the world? Are you sure it didn't go into a different jar?

**Comment by Zsashas** [comment]
It was the only jar, tested several times.

**Comment by coolAlias** [comment]
Please describe the exact steps to reproduce.

**Comment by Zsashas** [comment]
Find some naturally generated clay jars, toss an item in, right-click the jar.

**Comment by coolAlias** [comment]
Works perfectly fine for me - tested with ZSS v2.4 and Forge 10.13.4.1558.
