### ISSUE TITLE
[1.7.10] Crash with Automagy

### ISSUE THREAD

**Issue by Zsashas** [coolAlias/ZeldaSwordSkills#66]
The Ring of Splinching is causing issues again with those dang Wizzrobes. I can't remember if this actually got fixed the last time I brought it up, but this is the first issue to arise from this in quite some time.

https://github.com/Tuhljin/Automagy/issues/52

**Comment by coolAlias** [comment]
[Line 503](https://github.com/coolAlias/ZeldaSwordSkills/blob/master/src/main/java/zeldaswordskills/entity/mobs/EntityWizzrobe.java#L503) could potentially try to drop a null itemstack - oops :P

**Comment by Zsashas** [comment]
Looks like it's not just that Ring of Splinching, any Wizzrobe death has a chance of crashing.

**Comment by coolAlias** [comment]
Yeah. I thought I had fixed that long ago, but maybe it's in all that code I haven't released yet that it's been like a year since I've looked at...
