### ISSUE TITLE
hookshot,multishot not functioning on half of the hookshot targets placed within range

### ISSUE THREAD

**Issue by usafphoenix** [coolAlias/ZeldaSwordSkills#67]
making a skyblock hardcore map which includes custom-built ZSS dungeons utilizing hqm-progression and ZSS items to progress through the skyblock map. Having trouble figuring out why some of my hookshot targets are functioning as intended and others just result in a "automatic miss" sound or deflection of the hookshot arrow with no effect (user stays still) OR....hookshot draws player to a block opposite in direction to where i'm pointing. 
Problem is, some targets work fine....others don't work at all.

**Comment by usafphoenix** [comment]
note that occasionally, when not pointed at any blocks (trying to troubleshoot), the arrow from the hookshot will shoot straight, and then stray WAY off course left, right, up, down, backwards behind me or something totally unexpected.

**Comment by coolAlias** [comment]
This sounds like a bug that was fixed long ago - what ZSS and Forge version are you using?

**Comment by coolAlias** [comment]
@usafphoenix Can you please confirm that this is an issue and provide ZSS and Forge versions used in your testing?

**Comment by coolAlias** [comment]
Closing as not reproducible.
