### ISSUE TITLE
Set default warp locations

### ISSUE THREAD

**Issue by coolAlias** [coolAlias/ZeldaSwordSkills#68]
There needs to be a way for map makers to set default warp coordinates for each of the warp songs. The easiest solution would be to add config options, though it would probably be better if there were some way to set the coordinates in-game while creating the map.

**Comment by usafphoenix** [comment]
perhaps using a command. along the lines of: zssSetWarp {song} [optional: x, y z]
command uses player position if not explicitly given x,y,z
or just use config settings. The best pseudo code i can think of to handle it:

On event:learnedSongIsPlayed
if configOption.WarpOverrideEnabled==true {
 //check to make sure config values for coordinates are valid then attempt to teleport player
if overridesEnabled == true, but specific song has no coordinates pre-set, (or values are incomplete or invalid) check next case (continue with code as previously written)
}

**Comment by coolAlias** [comment]
No, I'm thinking for map-makers in game making a map, e.g. they place the warp block and then sneak activate it or something to set that block's coordinates as the default for when the player first learns that song (typically when the player is far away from said block).

**Comment by usafphoenix** [comment]
oh, that's a better idea.
