### ISSUE TITLE
Server crash when right clicking NPCs

### ISSUE THREAD

**Issue by Gamerbolts** [coolAlias/ZeldaSwordSkills#70]
Hi. I am making a modpack and saw you updated this mod and wanted to add it into my pack. I was testing it and spawn Zelda, Went to right click her and my server crashed. This is the error log I have http://pastebin.com/WKtF8APT

I know I do have a lot of mods 290 to be precise including customNPCs and MCA. Not too sure if one of those could be the issue?

Any help is appreciated. Thank you!

**Comment by coolAlias** [comment]
Thanks - I never did get around to testing things on a server...

**Comment by Gamerbolts** [comment]
Not a problem. I'll check for any other crashes and report them to you. Great find for my modpack! Thanks for fixing the issues
