### ISSUE TITLE
Ocarina Glitch

### ISSUE THREAD

**Issue by BrofistKittycat** [coolAlias/ZeldaSwordSkills#73]
I'm unable to press "down" in either of the ocarina screens, and I have no idea why. There's no crash or anything, I just can't press down. I'm using the latest for 1.7.10(2.5.1), but I have noticed that using older versions of ZSS seems to work. Any ideas/fixes? Plus, "down" is the only key I can't press. I can do the modifiers(W,A,S,D) and all other keys except for "down"(Space,Left,Right,Up).

**Comment by coolAlias** [comment]
That's quite a bizarre problem... I've tested it on my end and everything works perfectly.

Perhaps you have a mod conflict of some sort? Try playing with only ZSS installed to see if this is the issue.

If the issue persists, is your down arrow key working? If it is, then what version of Forge are you using? That shouldn't affect it, really, but at this point I have no idea what else it could be.

**Comment by BrofistKittycat** [comment]
I've tried just ZSS before, and that didn't work. However, for some reason, after playing for a couple more hours, it fixed itself? I was on my private server when it suddenly worked, and now I can play it in Singleplayer, too. Although, I do remember reinstalling ZSS, so I probably just had a bugged download.
