### ISSUE TITLE
Fatal error when z targeting

### ISSUE THREAD

**Issue by RetroGamerAndre** [coolAlias/ZeldaSwordSkills#79]
I'm currently enjoying all the mods that I used to use in 1.7.10 and that includes the ZSS mod, however I think there's a bug that causes a fatal error crash (doesn't leave a crash log, but it does boot me back to the multiplayer server select screen) whenever I z-target anything. I don't know what causes it and I would love to continue playing and be able to target my enemies. Any help would be appreciated and if I need to do anything more (pics, mods installed, etc.) don't hesitate to let me know. Thanks for the help!

RetroGamerAndre

Edit: adding the two pictures that happen in sequence to one another
![z-target crash part 1](https://user-images.githubusercontent.com/32158369/30719721-364cbd84-9eea-11e7-9e48-98fb1e22b572.PNG)
![z-target crash part 2](https://user-images.githubusercontent.com/32158369/30719722-364d67e8-9eea-11e7-8cdb-fb87b20ccc40.PNG)

Edit 2: Posting the log file for the bug

[2017-09-21-2.log.gz](https://github.com/coolAlias/ZeldaSwordSkills/files/1323063/2017-09-21-2.log.gz)

**Comment by coolAlias** [comment]
This is an issue with the Little Maid mod using a fake player that triggers events that are supposed to only fire for real players. I won't be addressing this issue any time soon, if ever. Sorry.
