### ISSUE TITLE
[1.7.10] Convert NPC

### ISSUE THREAD

**Issue by zHawky** [coolAlias/ZeldaSwordSkills#96]
I noticed that the convert to princess zelda still does not work in 1.7.10 version..
List of mods and forge that im use:
**1.7.10-Forge10.13.4.1566-1.7.10** or **1.7.10-Forge10.13.4.1558-1.7.10**
**1.7.10-zeldaswordskills-2.5.1**
Who have prior version please give a link for testing purposes.

BTW, playing around with Arcana RPG one of bosses become numb when ZSS is installed, 
called Cursed Remnant. In theory he inflicts constant damage to near animals and players after summoning, with zss he just push away with no damage. Bug or feature who knows. ¯ \ _(ツ)_ / ¯
Edit:  installed 1.7.10-zeldaswordskills-2.4, remnant stay numb, it mean something wrong in Arcana RPG.

**Comment by coolAlias** [comment]
It works fine for me:

1. Name a villager Zelda

2. Right-click on villager with Fairy Ocarina

3. Auto-converts if you converted at least once before, otherwise does a little mini-quest

**Comment by zHawky** [comment]
Well, it works! Thanks.
